### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by f0kx** [ianm1647/expandeddelight#19]
https://pastebin.com/ZvWuGqce

**Comment by washinoboku** [comment]
same problem

[crash-2022-08-11_23.59.32-client.txt](https://github.com/ianm1647/expandeddelight/files/9314466/crash-2022-08-11_23.59.32-client.txt)

**Comment by GhostGoesBinted** [comment]
https://pastebin.com/LDksjhWe

**Comment by Geethebluesky** [comment]
I'm getting the same error using ED 0.1.9. This started after I updated Farmer's Delight to 1.2.0 from 0.2.1.

They renamed a bunch of things and the registry seems to be called NOURISHMENT instead of NOURISHED now.

@ianm1647 are you planning on updating your Fabric mods still? Just so I know if I should remove them from my game or not.

**Comment by Sir-Caso** [comment]
[crash-2022-08-13_22.06.33-client.txt](https://github.com/ianm1647/expandeddelight/files/9332555/crash-2022-08-13_22.06.33-client.txt)

**Comment by Tempest-5ky** [comment]
Getting the same error! https://mclo.gs/eR52CDF

**Comment by Sammcb** [comment]
@ianm1647 any idea on if/when this mod will be updated? same as @Geethebluesky, I just want to know if I should remove it or not. Thanks!

**Comment by ianm1647** [comment]
Mod is currently updated, just gotta get through CurseForge verification and it's there! Thank you for the patience

**Comment by Sammcb** [comment]
Just curious, will there be an update for the 1.18.2 version as well? Thanks!

**Comment by Sammcb** [comment]
@ianm1647 ?

**Comment by ianm1647** [comment]
yeah i’ll have it done soon when i get the time

**Comment by Sammcb** [comment]
That's great to hear! Love the mod, and thanks so much for letting us know!
